// DamageReport.jsx — główny komponent wyświetlający raport szkody
//
// Przyjmuje sparsowany obiekt `report` z GPT-4o i renderuje go w sekcjach.
// Strukturalnie prosty — cała złożoność jest w App.jsx (streaming, parsowanie).

import SeverityBadge from "./SeverityBadge.jsx";
import DamageList from "./DamageList.jsx";

/**
 * @param {object} report - sparsowany JSON z GPT-4o
 * @param {File[]} images - File objects dla podglądu (bez bboxes w tej wersji)
 */
export default function DamageReport({ report, images }) {
  const { min, max, currency } = report.estimatedCostRange || {};

  return (
    <div className="space-y-5">
      {/* Nagłówek z severity */}
      <div className="bg-slate-900 border border-slate-800 rounded-xl p-5">
        <div className="flex items-start justify-between gap-4 mb-4">
          <div>
            <h2 className="text-white font-semibold mb-1">Damage Report</h2>
            <p className="text-xs text-slate-500">Generated by ClaimAI · GPT-4o</p>
          </div>
          <SeverityBadge severity={report.severity} />
        </div>

        {/* Uzasadnienie severity */}
        {report.severityReason && (
          <p className="text-sm text-slate-400 italic border-l-2 border-slate-700 pl-3">
            {report.severityReason}
          </p>
        )}
      </div>

      {/* Szacowany koszt naprawy */}
      {min !== undefined && max !== undefined && (
        <div className="bg-slate-900 border border-slate-800 rounded-xl p-5">
          <h3 className="text-xs font-semibold text-slate-500 uppercase tracking-wider mb-2">
            Estimated Repair Cost
          </h3>
          <p className="text-2xl font-bold text-white">
            {min.toLocaleString("pl-PL")}–{max.toLocaleString("pl-PL")}{" "}
            <span className="text-slate-400 text-lg font-normal">{currency || "PLN"}</span>
          </p>
        </div>
      )}

      {/* Podsumowanie dla likwidatora */}
      {report.claimSummary && (
        <div className="bg-slate-900 border border-slate-800 rounded-xl p-5">
          <h3 className="text-xs font-semibold text-slate-500 uppercase tracking-wider mb-3">
            Adjuster Summary
          </h3>
          <p className="text-sm text-slate-300 leading-relaxed">{report.claimSummary}</p>
        </div>
      )}

      {/* Wykryte uszkodzenia + dotknięte części */}
      <div className="bg-slate-900 border border-slate-800 rounded-xl p-5 space-y-5">
        <DamageList
          items={report.detectedDamage}
          title="Detected Damage"
          icon="🔎"
        />
        <DamageList
          items={report.affectedParts}
          title="Affected Parts"
          icon="🔧"
        />
      </div>

      {/* Rekomendowane działania */}
      {report.recommendedActions?.length > 0 && (
        <div className="bg-slate-900 border border-slate-800 rounded-xl p-5">
          <h3 className="text-xs font-semibold text-slate-500 uppercase tracking-wider mb-3 flex items-center gap-2">
            <span>📋</span>
            Recommended Actions
          </h3>
          <ol className="space-y-2">
            {report.recommendedActions.map((action, index) => (
              <li key={index} className="flex items-start gap-3 text-sm text-slate-300">
                <span className="flex-shrink-0 w-5 h-5 bg-blue-900 text-blue-300 rounded-full text-xs flex items-center justify-center font-bold">
                  {index + 1}
                </span>
                {action}
              </li>
            ))}
          </ol>
        </div>
      )}

      {/* Podgląd wgranych zdjęć */}
      {images?.length > 0 && (
        <div className="bg-slate-900 border border-slate-800 rounded-xl p-5">
          <h3 className="text-xs font-semibold text-slate-500 uppercase tracking-wider mb-3 flex items-center gap-2">
            <span>🖼️</span>
            Submitted Photos ({images.length})
          </h3>
          <div className="grid grid-cols-2 gap-2">
            {images.map((file, index) => (
              <img
                key={index}
                src={URL.createObjectURL(file)}
                alt={`Photo ${index + 1}`}
                className="w-full h-32 object-cover rounded-lg border border-slate-700"
              />
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
